version: "3"
services:
  backend:
    image: insoo223/contacts_back:name
    ports:
      - "5000:5000"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: insoo223/contacts_front:name
    ports:
      - "3000:3000"
    depends_on:
      - backend

